---
name: Net-Backpack
version: 1.14
author:
  - 'Dave Cross E<lt>dave@dave@mag-sol.comE<gt>'
abstract: Perl extension for interfacing with Backpack
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Net::Backpack:
    file: lib/Net/Backpack.pm
    version: 1.14
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
