---
name: Net-Backpack
version: 0.02
author:
  - Dave Cross E<lt>dave@dave@dave.org.ukE<gt>
abstract: Perl extension for interfacing with Backpack
license: perl
requires:
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Net::Backpack:
    file: lib/Net/Backpack.pm
    version: 0.02
generated_by: Module::Build version 0.261
